version: '3.4'

services: 
  
  api: 
    image: rest-api:latest
    restart: always
    command: apachectl -D FOREGROUND   
    volumes: 
      - ./:/var/www/html
    ports: 
      - 81:80
    external_links:
      - 'db'  
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    networks: 
      - theWorld  

networks:
  theWorld:
    external: true 